version: "3.7"

volumes:
   data:

services:
  database:
    image: postgres:14
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
      
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database 
    networks:
      - default
    ports:
      - "8080:8080"
volumes:
  data:      


  
    

